CREATE DATABASE GROCERYLIST;
USE GROCERYLIST;

CREATE TABLE `User` (
    `id` INT NOT NULL UNIQUE AUTO_INCREMENT,
     PRIMARY KEY(`id`),
    `name` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL UNIQUE,
    `password` VARCHAR(32) NOT NULL,
    `last_login` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `List` (
    `id` INT NOT NULL UNIQUE AUTO_INCREMENT,
     PRIMARY KEY(`id`),
     `user_id` INT NOT NULL,
     FOREIGN KEY(`user_id`) REFERENCES User(`id`),
    `name` VARCHAR(45) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `completed_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE `Item` (
    `id` INT NOT NULL UNIQUE AUTO_INCREMENT,
     PRIMARY KEY(`id`),
     `list_id` INT NOT NULL,
     FOREIGN KEY(`list_id`) REFERENCES List(`id`),
    `name` VARCHAR(45) NOT NULL,
    `quantity` INT DEFAULT 1,
    `price` FLOAT DEFAULT 0.00,
    `is_checked` BOOL DEFAULT FALSE,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);